export const menuItems = [
    { path: "/", name: "Home" },
    { path: "/b/column", name: "Column" },
    { path: "/b/color", name: "Color" },
    { path: "/b/table", name: "Table" },
    { path: "/b/alert", name: "Alert" },
    { path: "/b/button", name: "Button" },
    { path: "/b/btngroup", name: "Btn Group" },
    { path: "/b/badge", name: "Badge" },
    { path: "/b/progress", name: "Progress" },
    { path: "/b/spinner", name: "Spinner" },
    { path: "/b/pagination", name: "Pagination" },
    { path: "/b/listgroup", name: "List Group" },
    { path: "/b/card", name: "Card" },
    { path: "/b/dropdown", name: "Dropdown" },
    { path: "/b/collapse", name: "Collapse" },
    { path: "/b/navbar", name: "Navbar" },
    { path: "/b/carousel", name: "Carousel" },
    { path: "/b/modal", name: "Modal" },
    { path: "/b/tooltip", name: "Tooltip" },
    { path: "/b/popover", name: "Popover" },
    { path: "/b/toast", name: "Toast" },
    { path: "/b/scrollspy", name: "Scrollspy" },
    { path: "/b/utilities", name: "Utilities" },
    { path: "/b/flex", name: "Flex" },
];


export const svelteMenuItems = [
    { path: "/v", name: "Home" },
    { path: "/v/style", name: "Style" },
    { path: "/v/state", name: "State" },
    { path: "/v/derived", name: "Derived" },
    { path: "/v/effect", name: "Effect" },
    { path: "/v/props", name: "Props" },
    { path: "/v/logic", name: "Logic" },
    { path: "/v/event", name: "Event" },
];
