export const menuItems = [
    { path: "/", name: "Home" },
    { path: "/column", name: "Column" },
    { path: "/color", name: "Color" },
    { path: "/table", name: "Table" },
    { path: "/alert", name: "Alert" },
    { path: "/button", name: "Button" },
    { path: "/btngroup", name: "Btn Group" },
    { path: "/badge", name: "Badge" },
    { path: "/progress", name: "Progress" },
    { path: "/spinner", name: "Spinner" },
    { path: "/pagination", name: "Pagination" },
    { path: "/listgroup", name: "List Group" },
    { path: "/card", name: "Card" },
    { path: "/dropdown", name: "Dropdown" },
    { path: "/collapse", name: "Collapse" },
    { path: "/navbar", name: "Navbar" },
    { path: "/carousel", name: "Carousel" },
    { path: "/modal", name: "Modal" },
    { path: "/tooltip", name: "Tooltip" },
    { path: "/popover", name: "Popover" },
    { path: "/toast", name: "Toast" },
    { path: "/scrollspy", name: "Scrollspy" },
    { path: "/utilities", name: "Utilities" },
    { path: "/flex", name: "Flex" },
];


export const svelteMenuItems = [
    { path: "/v", name: "Home" },
    { path: "/v/style", name: "Style" },
    { path: "/v/state", name: "State" },
    { path: "/v/derived", name: "Derived" },
    { path: "/v/effect", name: "Effect" },
    { path: "/v/props", name: "Props" },
    { path: "/v/logic", name: "Logic" },
];
